#!/usr/bin/env bash
# Push from client a file

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
/etc/init.d/nginx start
