#!/usr/bin/env bash
# This script displays 10 "Holberton School" and the 9th time display Hi

i=1
while [ "$i" -le 10 ]
do
    echo "Holberton School"
    if [ "$i" == 9 ]; then
	echo "Hi"
    fi
    (( i++ ))
done
