#!/usr/bin/env bash
# this script prints 10 times Holberton School except 4tH and 8th

x=1
while [ "$x" -le 10 ]
do
    if [ "$x" -eq 4 ]; then
	echo "bad luck"
    elif [ "$x" -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    (( x++ ))
done
